import test from 'node:test';import assert from 'node:assert/strict';import {PI,ProcessDemo,compareScenario,csv} from '../web/model.js';
test('PI anti-windup stops accumulation at saturation and can recover',()=>{const p=new PI(2,1);for(let i=0;i<100;i++)assert.equal(p.update(100,.1),100);assert.equal(p.integral,0);assert.equal(p.update(-1,.1,50),47.9);});
test('normal sequence reaches running and tracks temperature/ratio',()=>{const m=new ProcessDemo();assert.equal(m.start(),true);m.run(180);assert.equal(m.state,'RUNNING');assert.ok(Math.abs(m.temperature-50)<.1);assert.ok(Math.abs(m.flowB/m.flowA-.8)<.001);});
test('missing permissive blocks start and loss during running trips',()=>{const m=new ProcessDemo();m.setUtility(false);assert.equal(m.start(),false);assert.equal(m.state,'IDLE');m.setUtility(true);m.start();m.run(35);m.setUtility(false);assert.equal(m.state,'TRIPPED');assert.equal(m.valveA,0);assert.equal(m.valveB,0);});
test('trip latches, requires restored conditions, and never auto-restarts',()=>{const m=new ProcessDemo({running:true});m.setQuality(false);assert.equal(m.state,'TRIPPED');m.run(10);assert.equal(m.resetTrip(),false);m.setQuality(true);assert.equal(m.state,'TRIPPED');assert.equal(m.resetTrip(),true);assert.equal(m.state,'IDLE');m.run(10);assert.equal(m.state,'IDLE');assert.equal(m.start(),true);});
test('high-high trip and reset threshold are separate from alarm',()=>{const m=new ProcessDemo({running:true});m.temperature=81;m.step(.1);assert.equal(m.state,'TRIPPED');assert.equal(m.resetTrip(),false);m.run(100);assert.ok(m.temperature<70);assert.equal(m.resetTrip(),true);});
test('new deterministic model rejects feed disturbance more quickly in cascade',()=>{const [single,cascade]=compareScenario();assert.ok(cascade.iae<single.iae);assert.ok(cascade.peak<single.peak);for(const r of [single,cascade])for(const x of r.history){assert.ok(Number.isFinite(x.temperature));assert.ok(x.valveA>=0&&x.valveA<=100);assert.ok(x.valveB>=0&&x.valveB<=100);}assert.deepEqual(compareScenario().map(x=>x.iae),[single.iae,cascade.iae]);});
test('setpoint tracking, strategy change and ratio follower remain bounded',()=>{const m=new ProcessDemo({running:true});const old=m.valveA;m.setStrategy('single');m.step(.1);assert.ok(Math.abs(m.valveA-old)<.1);m.setSetpoint(55);m.setRatio(1);m.run(180);assert.ok(Math.abs(m.temperature-55)<.1);assert.ok(Math.abs(m.flowB/m.flowA-1)<.005);assert.throws(()=>m.setSetpoint(NaN));assert.throws(()=>m.setRatio(9));assert.throws(()=>m.step(10));});
test('CSV names normalized data and agrees with exported rows',()=>{const m=new ProcessDemo({running:true});m.run(1);const text=csv(m.history);assert.match(text,/temperature_normalized/);assert.equal(text.trim().split('\n').length,m.history.length+1);});
