import {ProcessDemo,compareScenario,csv} from './model.js';import {evidence} from './evidence.js';
const $=id=>document.getElementById(id);let model=new ProcessDemo({running:true});model.run(25);let paused=false;
const fmt=(x,n=1)=>x==null?'—':x.toFixed(n);const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function chart(rows,series,{min=0,max=100}={}){const W=740,H=190,L=42,R=18,T=15,B=28;const end=rows.at(-1)?.time||1,start=rows[0]?.time||0,span=Math.max(1,end-start);const x=t=>L+(t-start)/span*(W-L-R),y=v=>H-B-(v-min)/(max-min)*(H-B-T);let s='<title>New simulated data; normalized values</title>';for(let i=0;i<=4;i++){const v=min+(max-min)*i/4;s+=`<line x1="${L}" y1="${y(v)}" x2="${W-R}" y2="${y(v)}" stroke="#e1e9e5"/><text x="4" y="${y(v)+3}">${v.toFixed(0)}</text>`;}for(let i=0;i<=4;i++){const t=start+span*i/4;s+=`<text x="${x(t)}" y="${H-8}" text-anchor="middle">${t.toFixed(0)} s</text>`;}for(const line of series){const points=rows.map(v=>`${x(v.time).toFixed(1)},${y(v[line.key]).toFixed(1)}`).join(' ');s+=`<polyline points="${points}" fill="none" stroke="${line.color}" stroke-width="2" ${line.dash?'stroke-dasharray="5 4"':''}/>`;}return s;}
function render(){const s=model.snapshot();$('state-label').textContent=s.state;$('status-dot').classList.toggle('tripped',s.state==='TRIPPED');$('clock').textContent=`t = ${fmt(s.time)} s`;$('temp-pv').textContent=fmt(s.temperature);$('temp-sp').textContent=fmt(s.sp);$('flow-a').textContent=fmt(s.flowA);$('flow-b').textContent=fmt(s.flowB);$('flow-sp').textContent=fmt(s.flowSP);$('ratio-pv').textContent=fmt(s.actualRatio,2);$('ratio-sp').textContent=fmt(s.ratio,2);$('strategy-label').textContent=model.strategy==='cascade'?'CASCADE + RATIO':'SINGLE LOOP + RATIO';$('strategy').value=model.strategy;$('setpoint').value=model.sp;$('setpoint-value').textContent=model.sp;$('ratio').value=model.ratio;$('ratio-value').textContent=fmt(model.ratio,2);$('utility').checked=model.utilityReady;$('quality').checked=model.signalHealthy;
 $('svg-temperature').textContent=fmt(s.temperature);$('svg-ratio').textContent='× '+fmt(s.ratio,2);$('svg-valve-a').textContent=`Valve ${fmt(s.valveA,0)}%`;$('svg-valve-b').textContent=`Valve ${fmt(s.valveB,0)}%`;$('valve-a-shape').style.opacity=s.valveA>.1?'1':'.35';$('valve-b-shape').style.opacity=s.valveB>.1?'1':'.35';$('vessel-fill').setAttribute('fill',s.state==='TRIPPED'?'#f1d4cc':'#d5e9e0');$('signal-explanation').textContent=model.strategy==='cascade'?'TIC → flow setpoint → FIC A → valve A. Measured flow A × ratio → FIC B → valve B.':'TIC → valve A directly. Measured flow A × ratio → FIC B → valve B. The inner feed-A controller is bypassed in this teaching mode.';
 $('start').disabled=model.state!=='IDLE';$('trip-reset').disabled=model.state!=='TRIPPED';$('stop').disabled=model.state==='TRIPPED'||model.state==='IDLE';document.querySelectorAll('[data-state]').forEach(x=>x.classList.toggle('active',x.dataset.state===model.state));$('alarm-count').textContent=model.alarms.length;$('alarms').innerHTML=model.alarms.length?model.alarms.map(a=>`<p><b>${escape(a.id)}</b><br>${escape(a.message)}</p>`).join(''):'<p class="clear">No active alarms</p>';$('events').innerHTML=model.events.slice(0,12).map(e=>`<li>${fmt(e.time)} s · ${escape(e.message)}</li>`).join('');
 const rows=model.history.filter((x,i)=>i%3===0||i===model.history.length-1);$('temp-chart').innerHTML=chart(rows,[{key:'temperature',color:'#286f5e'},{key:'sp',color:'#6385a1',dash:true}]);$('flow-chart').innerHTML=chart(rows,[{key:'flowA',color:'#286f5e'},{key:'flowB',color:'#bd872c'}]);$('pause').textContent=paused?'Resume':'Pause';}
function action(fn,message){fn();$('action-message').textContent=message||model.events[0]?.message||'';render();}
$('pause').onclick=()=>{paused=!paused;render();};$('advance').onclick=()=>action(()=>model.run(30),'Advanced 30 simulated seconds');$('idle').onclick=()=>action(()=>{model=new ProcessDemo();paused=true;},'Reset to idle. Check permissives, then start the sequence.');$('start').onclick=()=>action(()=>{if(model.start())paused=false;});$('stop').onclick=()=>action(()=>model.stop());$('trip-reset').onclick=()=>action(()=>model.resetTrip());$('strategy').onchange=e=>action(()=>model.setStrategy(e.target.value));$('setpoint').oninput=e=>action(()=>model.setSetpoint(Number(e.target.value)));$('ratio').oninput=e=>action(()=>model.setRatio(Number(e.target.value)));$('utility').onchange=e=>action(()=>model.setUtility(e.target.checked));$('quality').onchange=e=>action(()=>model.setQuality(e.target.checked));$('flow-disturbance').onclick=()=>action(()=>model.setDisturbance(-15,0));$('heat-disturbance').onclick=()=>action(()=>model.setDisturbance(0,15));$('clear-disturbance').onclick=()=>action(()=>model.setDisturbance(0,0));$('export').onclick=()=>{const blob=new Blob([csv(model.history)],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='normalized-control-demo.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('compare').onclick=()=>{const r=compareScenario();const a=r[0],b=r[1];$('comparison-output').innerHTML=`<table><thead><tr><th>STRATEGY</th><th>IAE (NORMALIZED × s)</th><th>PEAK ABS. ERROR</th></tr></thead><tbody>${r.map(x=>`<tr><td>${x.strategy==='single'?'Single loop + ratio':'Cascade + ratio'}</td><td>${fmt(x.iae,2)}</td><td>${fmt(x.peak,2)}</td></tr>`).join('')}</tbody></table><svg id="comparison-chart" viewBox="0 0 740 190" class="trend" role="img" aria-label="Teaching-model comparison of two strategies"></svg><p>Green: cascade · amber: single loop. Fixed PI settings and linear dynamics; no experimental plant data.</p>`;const rows=a.history.filter((x,i)=>i%3===0).map((x,i)=>({time:x.time,single:x.temperature,cascade:b.history[i*3]?.temperature||50}));$('comparison-chart').innerHTML=chart(rows,[{key:'cascade',color:'#286f5e'},{key:'single',color:'#bd872c'}],{min:45,max:51});};
$('gallery').innerHTML=evidence.map(x=>`<button class="evidence-image" data-asset="${x.file}"><img src="assets/${x.file}" loading="lazy" alt="${escape(x.caption)}"><strong>${escape(x.caption)}</strong><small>Fig. ${x.figure} · PDF page ${x.page}</small></button>`).join('');document.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{const e=evidence.find(x=>x.file===b.dataset.asset);$('enlarged-image').src='assets/'+e.file;$('enlarged-image').alt=e.caption;$('image-caption').textContent=`${e.caption} · Thesis figure ${e.figure} · PDF page ${e.page}`;$('image-dialog').showModal();});$('close-image').onclick=()=>$('image-dialog').close();
render();setInterval(()=>{if(!paused){for(let i=0;i<4;i++)model.step(.1);render();}},200);
